
import { bootstrapApplication } from '@angular/platform-browser';
import { provideZonelessChangeDetection } from '@angular/core';
import { AppComponent } from './src/app.component';
import { 
  LucideAngularModule, 
  Search, 
  ArrowLeftRight, 
  Lightbulb, 
  Cpu, 
  Eye, 
  ShoppingCart, 
  Layout,
  CreditCard,
  Cloud, 
  Stethoscope, 
  Landmark, 
  User, 
  Handshake, 
  Network, 
  Bolt, 
  PieChart, 
  Globe, 
  TrendingUp, 
  Star, 
  Phone, 
  Map, 
  Rocket, 
  Calendar, 
  ArrowRight, 
  FileText, 
  Database, 
  Share2, 
  MessageSquare, 
  Plus, 
  AlertTriangle, 
  EyeOff, 
  Lock, 
  Zap, 
  Target, 
  Shield,
  Sparkles,
  Brain,
  ShieldCheck,
  Wand2,
  CheckCircle2,
  Users,
  BarChart3,
  Layers,
  ZapOff,
  History,
  ArrowUpRight,
  ChevronRight
} from 'lucide-angular';
import { importProvidersFrom } from '@angular/core';

bootstrapApplication(AppComponent, {
  providers: [
    provideZonelessChangeDetection(),
    importProvidersFrom(LucideAngularModule.pick({ 
      Search, 
      ArrowLeftRight, 
      Lightbulb, 
      Cpu, 
      Eye, 
      ShoppingCart, 
      Layout,
      CreditCard,
      Cloud, 
      Stethoscope, 
      Landmark, 
      User, 
      Handshake, 
      Network, 
      Bolt, 
      PieChart, 
      Globe, 
      TrendingUp, 
      Star, 
      Phone, 
      Map, 
      Rocket, 
      Calendar, 
      ArrowRight, 
      FileText, 
      Database, 
      Share2, 
      MessageSquare, 
      Plus, 
      AlertTriangle, 
      EyeOff, 
      Lock, 
      Zap, 
      Target, 
      Shield,
      Sparkles,
      Brain,
      ShieldCheck,
      Wand2,
      CheckCircle2,
      Users,
      BarChart3,
      Layers,
      ZapOff,
      History,
      ArrowUpRight,
      ChevronRight
    }))
  ]
}).catch((err) => console.error(err));

// AI Studio always uses an `index.tsx` file for all project types.
